services:
  dev-db:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 825273
      POSTGRES_DB: quranDailyDevDB
    networks:
      - noNetwork
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 825273
      POSTGRES_DB: quranDailyTestDB
    networks:
      - noNetwork
networks:
  noNetwork:
